# --- Revised Beets Configuration for Automated Deep Enrichment ---

directory: /music/organized
library: /config/musiclibrary.db
log: /config/beetslog.txt    # Log all activity for easier debugging

# Enable multithreading for faster processing
threaded: yes
original_date: yes

# --- Import Settings: More Robust and Less Strict ---
import:
  move: no
  copy: yes                   # Explicitly copy files, keeping originals safe
  write: yes
  incremental: no             # IMPORTANT: Set to 'no' for the first big import, then 'yes' for later runs
  timid: no                   # Fully non-interactive, no prompts
  autotag: yes
  quiet: no                   # Disable quiet mode to see progress and errors on the first run
  group_albums: yes
  
  # More forgiving actions for different match qualities
  default_action: apply       # Apply the best match found
  strong_rec_action: apply    # Automatically apply any strong matches
  medium_rec_action: apply    # Automatically apply medium-confidence matches
  none_rec_action: asis       # CRITICAL: If no match is found, import the file as-is instead of skipping

# --- Plugins: Added Fingerprinting and Filename Parsing ---
plugins:
  - chroma                    # For audio fingerprinting (most powerful feature for messy files)
  - fromfilename              # Helps guess tags from filenames
  - fetchart
  - embedart
  - lastgenre
  - duplicates
  - scrub
  - lyrics
  - web
  - info

# --- Matching: Use Fingerprinting and Tweak Thresholds ---
match:
  strong_rec_thresh: 0.04     # Default is 0.04, you can lower to be more aggressive, e.g., 0.02
  medium_rec_thresh: 0.25     # Default is 0.25, increase to be more selective on medium matches
  # Give more weight to fingerprints to improve accuracy
  distance_weights:
    chroma: 10.0

# --- Plugin Settings for Full Automation ---

# AcoustID/Chroma for audio fingerprinting
# Note: The docker container might need pyacoustid installed.
chroma:
  auto: yes                   # Automatically fingerprint every track

# Scrub away unwanted tags after processing
scrub:
  auto: yes

# Album art settings
fetchart:
  auto: yes
  sources: [coverart, musicbrainz, amazon, google, fanarttv, albumart] # More sources for better art
  
embedart:
  auto: yes
  maxwidth: 1200              # High-resolution artwork

# Genre settings
lastgenre:
  auto: yes
  source: album

# Lyrics settings
lyrics:
  auto: yes
  fallback: ''

# Web interface (no changes)
web:
  host: 0.0.0.0
  port: 8337

# Path formatting (no changes)
paths:
  default: $albumartist/$album%aunique{}/$track - $title
  singleton: Singles/$artist - $title
  comp: Compilations/$album%aunique{}/$track - $title

