# Optimized non-interactive Beets configuration with metadata enrichment
directory: /music/organized
library: /config/musiclibrary.db
log: /config/beets.log     # Added for debugging

# Import settings (enhanced for non-interactive automation)
import:
  move: no                  # Copy files (keep originals safe)
  copy: yes                 # Explicitly copy
  write: yes                # Write metadata to files
  incremental: yes          # Only process new files
  quiet_fallback: asis      # Import as-is if no match (reduces skipping)
  timid: no                 # No confirmation prompts
  autotag: yes              # Enable MusicBrainz matching
  quiet: yes                # Suppress unnecessary output
  default_action: apply     # Auto-apply best matches without prompting
  none_rec_action: asis     # Import as-is for no-matches (key to reduce skipping)
  detail: no                # No detailed prompts
  group_albums: yes         # Group tracks into albums
  strong_rec_thresh: 0.02   # Lower threshold for accepting matches (more aggressive)
  medium_rec_thresh: 0.20   # Adjusted for better matching

# Plugins for rich metadata
plugins:
  - chroma                  # Audio fingerprinting (helps with unmatched tracks)
  - fromfilename            # Guess tags from filenames
  - fetchart
  - embedart
  - lastgenre
  - duplicates
  - scrub
  - lyrics
  - web
  - info

# Matching: Prioritize fingerprinting
match:
  strong_rec_thresh: 0.02   # More lenient for auto-apply
  medium_rec_thresh: 0.20
  distance_weights:
    chroma: 10.0            # High weight on fingerprints

# Album art settings
fetchart:
  auto: yes
  sources: [coverart, musicbrainz, amazon, google, fanarttv, albumart]

embedart:
  auto: yes
  maxwidth: 1200

# Genre settings
lastgenre:
  auto: yes
  source: album

# Lyrics settings
lyrics:
  auto: yes
  fallback: ''

# Web interface
web:
  host: 0.0.0.0
  port: 8337

# Path formatting
paths:
  default: $albumartist/$album%aunique{}/$track - $title
  singleton: Singles/$artist - $title
  comp: Compilations/$album%aunique{}/$track - $title
