# --- Fully Automated Beets Configuration for Unattended Enrichment ---

directory: /music/organized
library: /config/musiclibrary.db
log: /config/beetslog.txt # Central log file for all operations

# Performance settings
threaded: yes
original_date: yes

# --- Import Settings: Designed for Full Automation ---
import:
  move: no                  # Copy files (keep originals safe)
  copy: yes                 # Explicitly copy
  write: yes                # Write metadata to files
  incremental: no             # Process all files on the first run. Set to 'yes' for later.
  timid: no                   # No confirmation prompts for strong matches
  autotag: yes                # Enable MusicBrainz matching
  group_albums: yes           # Keep this enabled, but we'll control its behavior with command flags.

  # --- CRITICAL: Automatic Actions for All Match Levels ---
  # This section ensures the import never stops to ask for input.
  strong_rec_action: apply    # Automatically apply strong matches
  medium_rec_action: apply    # Automatically apply medium matches
  weak_rec_action: asis       # **THE FIX**: For weak matches (like your 15% example), import the track as-is instead of asking.
  none_rec_action: asis       # If no match is found, import as-is. This prevents skipping.

# --- Plugins: Corrected and Optimized ---
plugins:
  - chroma                    # Audio fingerprinting
  - from_filename             # **CORRECTED NAME**: Guesses tags from filenames. (was 'fromfilename')
  - fetchart
  - embedart
  - lastgenre
  - duplicates
  - scrub
  - lyrics
  - web
  - info

# --- Matching Engine: Fine-tuned for Automation ---
match:
  strong_rec_thresh: 0.04
  medium_rec_thresh: 0.25
  # Give more weight to audio fingerprints for higher accuracy on files with bad text metadata
  distance_weights:
    chroma: 10.0

# --- Plugin Settings for Automation ---

chroma:
  auto: yes                   # Automatically fingerprint every track

scrub:
  auto: yes                   # Automatically clean unwanted tags

fetchart:
  auto: yes
  sources: [coverart, musicbrainz, amazon, google, fanarttv, albumart]

embedart:
  auto: yes
  maxwidth: 1200

lastgenre:
  auto: yes
  source: album
  
lyrics:
  auto: yes
  fallback: ''

web:
  host: 0.0.0.0
  port: 8337

# --- File Organization Paths ---
paths:
  default: $albumartist/$album%aunique{}/$track - $title
  singleton: Singles/$artist/$artist - $title
  comp: Compilations/$album%aunique{}/$track - $title
