# Beets configuration for Lucky's Music Empire
directory: /music/organized
library: /config/musiclibrary.db

# FIXED: Non-interactive import settings
import:
  move: no                    # Keep originals, copy to organized
  write: yes                  # Write metadata to files
  duplicate_action: merge     # Handle duplicates intelligently
  incremental: yes            # Only process new files
  quiet_fallback: skip       # Skip unidentifiable tracks WITHOUT prompting
  timid: no                   # Don't ask for confirmation
  autotag: yes               # Enable automatic tagging
  quiet: no                  # Show progress but don't prompt
  default_action: apply      # Apply best match automatically
  none_rec_action: skip      # Skip items with no recommendations
  strong_rec_thresh: 0.04    # Lower threshold for accepting matches
  medium_rec_thresh: 0.25    # Medium confidence threshold
  
# Enable core plugins
plugins: [
  fetchart,
  embedart,
  lastgenre,
  duplicates,
  info,
  web,
  scrub
]

# MusicBrainz settings
musicbrainz:
  searchlimit: 10

# Album art settings
fetchart:
  auto: yes
  sources: coverart musicbrainz amazon google

# Embed artwork
embedart:
  auto: yes
  maxwidth: 1000

# Genre classification
lastgenre:
  auto: yes
  source: album

# Web interface
web:
  host: 0.0.0.0
  port: 8337

# Path formatting for organized music
paths:
  default: $albumartist/$album%aunique{}/$track - $title
  singleton: Non-Album/$artist - $title
  comp: Compilations/$album%aunique{}/$track - $title

# Duplicate handling
duplicates:
  album: no
  checksum: no
  copy: /music/duplicates
  move: no
  strict: no
  tiebreak:
    items: [bitrate, length]
