directory: /music/organized
library:   /config/musiclibrary.db

import:
  move: no
  copy: yes
  write: yes
  incremental: no
  resume: no
  quiet_fallback: asis
  timid: no
  autotag: yes
  quiet: yes
  duplicate_action: skip
  group_albums: yes
  strong_rec_thresh: 0.04
  medium_rec_thresh: 0.15

plugins: [chroma, fetchart, embedart, duplicates]

# minimal art
fetchart:
  auto: yes
  sources: coverart musicbrainz
embedart:
  auto: yes
  maxwidth: 800
