# Non-interactive Beets configuration
directory: /music/organized
library: /config/musiclibrary.db

# FIXED: Fully non-interactive import settings
import:
  move: no                    # Copy files, don't move them
  write: yes                  # Write metadata to files
  incremental: yes            # Only process new files
  quiet_fallback: skip       # Skip unidentifiable tracks
  timid: no                   # Don't ask for confirmation
  autotag: no                 # Disable MusicBrainz matching entirely
  quiet: yes                  # Suppress prompts
  default_action: skip        # Default action for ambiguous matches
  none_rec_action: skip       # Skip items with no recommendations
  detail: no                  # Don't show detailed info
  group_albums: no            # Don't try to group into albums
  
# Enable minimal plugins only
plugins: [
  fetchart,
  embedart,
  web
]

# Web interface
web:
  host: 0.0.0.0
  port: 8337

# Simple path formatting
paths:
  default: $albumartist/$album%aunique{}/$track - $title
  singleton: Singles/$artist - $title
  
# Album art settings (minimal)
fetchart:
  auto: no                    # Don't auto-fetch (avoid delays)
  
embedart:
  auto: no                    # Don't auto-embed (avoid delays)
