# Beets configuration for Lucky's Music Empire
directory: /music/organized
library: /config/musiclibrary.db

# Import settings
import:
  move: no
  write: yes
  duplicate_action: merge
  incremental: yes
  quiet_fallback: skip
  timid: no
  
# Enable core plugins (removed problematic ones)
plugins: [
  fetchart,
  embedart,
  lastgenre,
  duplicates,
  info,
  web,
  scrub
]

# MusicBrainz settings
musicbrainz:
  searchlimit: 10

# Album art settings
fetchart:
  auto: yes
  sources: coverart musicbrainz amazon google

# Embed artwork
embedart:
  auto: yes
  maxwidth: 1000

# Genre classification
lastgenre:
  auto: yes
  source: album

# Web interface
web:
  host: 0.0.0.0
  port: 8337

# Path formatting for organized music
paths:
  default: $albumartist/$album%aunique{}/$track - $title
  singleton: Non-Album/$artist - $title
  comp: Compilations/$album%aunique{}/$track - $title

# Duplicate handling
duplicates:
  album: no
  checksum: no
  copy: /music/duplicates
  move: no
  strict: no
  tiebreak:
    items: [bitrate, length]

# Clean up patterns (proper YAML format)
rewrite:
  '^\\.': _          # Replace leading dots
  '[/\\\\]': _       # Replace slashes
  '^-': _            # Replace leading dashes
  '\\s+$': ''        # Remove trailing whitespace
