# Optimized non-interactive Beets configuration with metadata enrichment
directory: /music/organized
library: /config/musiclibrary.db

# Import settings (enhanced for automation and metadata)
import:
  move: no                    # Copy files (keep originals safe)
  write: yes                  # Write metadata to files
  incremental: yes            # Only process new files
  quiet_fallback: skip       # Skip unidentifiable tracks
  timid: no                   # No confirmation prompts
  autotag: yes                # Enable MusicBrainz matching for metadata
  quiet: yes                  # Suppress unnecessary output
  default_action: apply       # Auto-apply best matches
  none_rec_action: skip       # Skip no-match items
  detail: no                  # No detailed prompts
  group_albums: yes           # Group tracks into albums
  
# Enable plugins for rich metadata
plugins: [
  fetchart,                   # Fetch album artwork
  embedart,                   # Embed artwork in files
  lastgenre,                  # Add genre tags via Last.fm
  duplicates,                 # Detect and handle duplicates
  info,                       # Extended track info
  web,                        # Web interface
  scrub,                      # Clean metadata
  lyrics                      # Fetch lyrics
]

# MusicBrainz settings (for better matching)
musicbrainz:
  searchlimit: 10             # More search results for accuracy

# Album art settings (auto-enabled)
fetchart:
  auto: yes                   # Auto-fetch artwork
  sources: coverart musicbrainz amazon google  # Multiple sources for best results
  
embedart:
  auto: yes                   # Auto-embed artwork
  maxwidth: 1000              # High-res images

# Genre classification
lastgenre:
  auto: yes                   # Auto-add genres
  source: album               # Use album-level genres

# Lyrics settings
lyrics:
  auto: yes                   # Auto-fetch lyrics
  fallback: ''                # No fallback if not found

# Web interface
web:
  host: 0.0.0.0
  port: 8337

# Path formatting
paths:
  default: $albumartist/$album%aunique{}/$track - $title
  singleton: Singles/$artist - $title
  comp: Compilations/$album%aunique{}/$track - $title
