# Enhanced non-interactive Beets configuration
directory: /music/organized
library: /config/musiclibrary.db

# Non-interactive import with safe autotagging
import:
  move: no                    # Copy files, preserve originals
  write: yes                  # Write metadata to files
  incremental: yes            # Only process new files
  quiet_fallback: skip       # Skip unidentifiable tracks
  timid: no                   # No confirmation prompts
  autotag: yes                # Enable MusicBrainz matching (non-interactive with thresholds)
  quiet: yes                  # Suppress output
  default_action: apply       # Auto-apply good matches
  none_rec_action: skip       # Skip no-match items
  detail: no                  # No detailed output
  group_albums: yes           # Group into albums (fixes Albums: 0)
  strong_rec_thresh: 0.1      # Accept high-confidence matches automatically
  medium_rec_thresh: 0.3      # Accept medium matches
  low_rec_thresh: 0.5         # Skip low-confidence

# Plugins for enrichment (including lyrics)
plugins: [
  fetchart,                   # Album art
  embedart,                   # Embed art
  lastgenre,                  # Genres
  duplicates,                 # Deduplication
  info,                       # Extra info
  web,                        # Web UI
  scrub,                      # Clean tags
  lyrics                      # Lyrics fetching
]

# Web interface
web:
  host: 0.0.0.0
  port: 8337

# Path formatting
paths:
  default: $albumartist/$album%aunique{}/$track - $title
  singleton: Singles/$artist - $title

# Album art (auto-enabled)
fetchart:
  auto: yes                   # Auto-fetch art
  sources: coverart musicbrainz amazon google
  
embedart:
  auto: yes                   # Auto-embed art
  maxwidth: 1000

# Lyrics (auto-fetch during import)
lyrics:
  auto: yes                   # Enable auto-fetch
  fallback: ''                # No fallback text
  force: no                   # Don't overwrite existing

# Deduplication (stricter)
duplicates:
  album: yes                  # Check by album
  checksum: yes               # Use audio checksums
  copy: /music/duplicates     # Move duplicates here
  strict: yes                 # Strict matching
  tiebreak:
    items: [bitrate, length]  # Prefer higher quality
