services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    restart: unless-stopped
    ports:
      - "4533:4533"
    environment:
      # Core Settings
      - ND_MUSICFOLDER=/music
      - ND_UIWELCOMEMESSAGE="🎵 Lucky's Music Empire"
      - ND_LOGLEVEL=info
      
      # IMPROVED: Scanning & Performance
      - ND_SCANSCHEDULE=@every 10m                    # More frequent scans for new downloads
      - ND_SCANINTERVAL=5s                            # Faster individual file scanning
      - ND_AUTOIMPORTPLAYLISTS=true                   # Auto-import M3U playlists
      - ND_IGNOREDARTICLES=The,El,La,Los,Las,Le,Les   # Better sorting (ignore "The", etc.)
      
      # IMPROVED: Transcoding & Cache
      - ND_TRANSCODINGCACHESIZE=2GB                   # Increased cache for better performance
      - ND_ENABLETRANSCODINGCACHE=true                # Enable transcoding cache
      - ND_FFMPEGPATH=/usr/bin/ffmpeg                 # Explicit FFmpeg path
      
      # IMPROVED: User Experience
      - ND_SESSIONTIMEOUT=72h                         # Extended session (3 days)
      - ND_ENABLEDOWNLOADS=true                       # Allow downloads
      - ND_ENABLESHARING=true                         # Enable sharing features
      - ND_ENABLESTARRATING=true                      # Enable 5-star rating system
      - ND_ENABLEGRAVATAR=true                        # User profile pictures
      - ND_DEFAULTTHEME=Dark                          # Dark theme by default
      
      # IMPROVED: Playlist & Organization
      - ND_MAXSIDEBARPLAYLISTS=50                     # Show more playlists in sidebar
      - ND_PLAYLISTSPATH=/music/playlists             # Dedicated playlist folder
      - ND_COVERARTPRIORITY=embedded,cover.*,folder.*,front.*  # Album art priority
      
      # IMPROVED: External Services
      - ND_ENABLEEXTERNALSERVICES=true                # Last.fm, Spotify scrobbling
      - ND_LASTFM_ENABLED=true                        # Enable Last.fm integration
      
      # IMPROVED: Performance & Stability
      - ND_ENABLEGZIP=true                            # Enable gzip compression
      - ND_REVERSEPROXYUSERHEADER=""                  # For reverse proxy setups
      - ND_REVERSEPROXYWHITELIST=""                   # Security for reverse proxy
      
    volumes:
      - ./navidrome-data:/data
      - /music:/music:ro
    user: "0:0"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:4533/ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  music-discovery-ui:
    build: .
    container_name: music-discovery-ui
    restart: unless-stopped
    ports:
      - "8501:8501"
    environment:
      - TZ=America/Chicago
    volumes:
      - /music:/music
    depends_on:
      - navidrome
