services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    restart: unless-stopped
    ports:
      - "4533:4533"
    environment:
      # Core Settings
      - ND_MUSICFOLDER=/music/organized  # CHANGED: Point to organized library
      - ND_UIWELCOMEMESSAGE="🎵 Lucky's Enhanced Music Empire"
      - ND_LOGLEVEL=info
      
      # IMPROVED: Scanning & Performance
      - ND_SCANSCHEDULE=@every 5m        # More frequent for Beets-processed files
      - ND_SCANINTERVAL=3s               # Faster scanning
      - ND_AUTOIMPORTPLAYLISTS=true
      - ND_IGNOREDARTICLES=The,El,La,Los,Las,Le,Les
      
      # IMPROVED: Transcoding & Cache
      - ND_TRANSCODINGCACHESIZE=3GB      # Increased for high-quality files
      - ND_ENABLETRANSCODINGCACHE=true
      - ND_FFMPEGPATH=/usr/bin/ffmpeg
      
      # IMPROVED: User Experience
      - ND_SESSIONTIMEOUT=72h
      - ND_ENABLEDOWNLOADS=true
      - ND_ENABLESHARING=true
      - ND_ENABLESTARRATING=true
      - ND_ENABLEGRAVATAR=true
      - ND_DEFAULTTHEME=Dark
      
      # IMPROVED: Playlist & Organization
      - ND_MAXSIDEBARPLAYLISTS=100       # More playlists for organized library
      - ND_PLAYLISTSPATH=/music/playlists
      - ND_COVERARTPRIORITY=embedded,cover.*,folder.*,front.*
      
      # ENHANCED: Last.fm Integration
      - ND_ENABLEEXTERNALSERVICES=true
      - ND_LASTFM_ENABLED=true
      - ND_LASTFM_APIKEY=f16d5f29d2118e1ee559857954814580
      - ND_LASTFM_SECRET=255404336083f46bbbc9b1fa4217cff2
      - ND_LASTFM_LANGUAGE=en
      
      # IMPROVED: Performance & Stability
      - ND_ENABLEGZIP=true
      - ND_REVERSEPROXYUSERHEADER=""
      - ND_REVERSEPROXYWHITELIST=""
      
    volumes:
      - ./navidrome-data:/data
      - /music:/music:ro  # Read-only access to all music
    user: "0:0"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:4533/ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  music-discovery-ui:
    build: .
    container_name: music-discovery-ui
    restart: unless-stopped
    ports:
      - "8501:8501"
    environment:
      - TZ=America/Chicago
      # ENHANCED: API credentials for the app
      - GENIUS_CLIENT_ID=BzzijSLkgTY7xDCzU4RqVy6FUTFWBF_whOtldgZcbF5MlDKg3pymXgE9gLwZ8dZE
      - GENIUS_CLIENT_SECRET=k-eyd0u1lg7p60R_ZOr6WesnYUCpHMzEcHqmhZZ-6lto6LaH72yXEUc9mHc5HL6rf87B-c4ob6J9CEAY4sc9fQ
      - LASTFM_API_KEY=f16d5f29d2118e1ee559857954814580
      - LASTFM_SECRET=255404336083f46bbbc9b1fa4217cff2
    volumes:
      - /music:/music 
      - ./beets-config:/config  # ADDED: Access to Beets config
    depends_on:
      - navidrome
  
  beets:
    image: lscr.io/linuxserver/beets:latest
    container_name: beets
    restart: unless-stopped
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Chicago
      - BEETSDIR=/config
    ports:
      - "8337:8337"
    volumes:
      - ./beets-config:/config
      - /music:/music
      - /music/organized:/music/organized  # ADDED: Explicit organized mount
      - /music/duplicates:/music/duplicates  # ADDED: Duplicates handling
    depends_on:
      - navidrome
